name: helpin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  firebase_core: ^3.13.0
  cloud_functions: ^5.4.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_pic1.png
